local:
  dialect: postgres
  database: engine_local
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/engine_test?sslmode=disable"}}
