
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/DataDog/datadog-go"
  version = "2.0.0"

[[constraint]]
  name = "github.com/algolia/algoliasearch-client-go"
  version = "2.21.3"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.78"

[[constraint]]
  name = "github.com/bitly/go-nsq"
  version = "1.0.7"

[[constraint]]
  name = "github.com/bugsnag/bugsnag-go"
  version = "1.3.0"

[[constraint]]
  name = "github.com/edganiukov/fcm"
  version = "0.2.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  branch = "master"
  name = "github.com/kr/pretty"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/gobuffalo/pop"
  version = "4.0.6"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/sendgrid/sendgrid-go"
  version = "3.4.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.7.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "github.com/josephburnett/jd"

[[constraint]]
  branch = "master"
  name = "golang.org/x/tools"

[[constraint]]
  branch = "master"
  name = "github.com/1l0/identicon"

[[constraint]]
  branch = "master"
  name = "go.uber.org/ratelimit"

[[constraint]]
  name = "github.com/vektah/gqlgen"
  version = "0.2.1"

[[constraint]]
  name = "github.com/nats-io/go-nats"
  version = "1.6.0"

[[constraint]]
  name = "github.com/gofrs/uuid"
  version = "3.1.2"
